"""Reusable high-level simulation presets."""

from evo_engine.presets.reference_ecology import (
    ReferenceEcology,
    ReferenceEcologyConfig,
    ReferenceExplorationMovement,
    ReferenceGaussianMovement,
    ReferenceMatingTypeInvestmentScales,
    ReferenceMooreMovement,
    ReferencePhysiologicalTradeoffs,
    ReferenceTraitValues,
    ReferenceUniformMovement,
    ReferenceVonNeumannMovement,
    build_reference_ecology,
    build_reference_engine,
    build_reference_founder_genome,
    build_reference_genetic_architecture,
    build_reference_reproductive_investment,
    build_reference_simulation,
    build_reference_spec,
    build_reference_world,
)

__all__ = [
    "ReferenceEcology",
    "ReferenceEcologyConfig",
    "ReferenceExplorationMovement",
    "ReferenceGaussianMovement",
    "ReferenceMatingTypeInvestmentScales",
    "ReferenceMooreMovement",
    "ReferencePhysiologicalTradeoffs",
    "ReferenceTraitValues",
    "ReferenceUniformMovement",
    "ReferenceVonNeumannMovement",
    "build_reference_ecology",
    "build_reference_engine",
    "build_reference_founder_genome",
    "build_reference_genetic_architecture",
    "build_reference_reproductive_investment",
    "build_reference_simulation",
    "build_reference_spec",
    "build_reference_world",
]